name: Build & Release (Windows)

on:
  push:
    tags:
      - "v*.*.*"  
  workflow_dispatch: {} 
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path "requirements-dev.txt") {
            pip install -r requirements-dev.txt
          } elseif (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          }

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          ./build.ps1 -Clean

      - name: Install Inno Setup
        shell: pwsh
        run: |
          choco install innosetup -y
          $Env:Path += ";C:\Program Files (x86)\Inno Setup 6"
          iscc.exe /Qp installer.iss

      
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-Atlas
          path: dist/Atlas/**

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Atlas-Installer
          path: |
            Output\*.exe
            .\Atlas-Setup-*.exe
            .\Output\Atlas-Setup-*.exe

      
      - name: Attach assets to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Output\*.exe
            Atlas-Setup-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}